### ISSUE TITLE
Cannot run server v1.0.0-rc.1

### ISSUE THREAD

**Issue by yuri-sergiichuk** [urish/firebase-server#123]
While trying to run the server that is installed globally I'm receiving the following stack trace:
```javascript
firebase-server --verbose
module.js:549
    throw err;
    ^

Error: Cannot find module '../index.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/<HOME_DIR>/.nvm/versions/node/v8.11.2/lib/node_modules/firebase-server/bin/firebase-server.js:48:25)
    at after (/home/<HOME_DIR>/.nvm/versions/node/v8.11.2/lib/node_modules/firebase-server/node_modules/cli/cli.js:1057:18)
    at Object.cli.main (/home/<HOME_DIR>/.nvm/versions/node/v8.11.2/lib/node_modules/firebase-server/node_modules/cli/cli.js:1062:9)
    at Object.<anonymous> (/home/<HOME_DIR>/.nvm/versions/node/v8.11.2/lib/node_modules/firebase-server/bin/firebase-server.js:25:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```

Steps to reproduce:
1. Install node v.8.11.2, e.g.: `nvm install 8.11.2`, `nvm use`.
1. Install npm v.6.0.1: `npm install npm -g`.
1. Install Firebase-server: `npm install firebase-server@1.0.0-rc.1 -g`.
1. Run the server: `firebase-server --verbose`.
1. The stack trace is shown.

v.0.12.0 works OK.

**Comment by urish** [comment]
Fixed in 1.0.0-rc.2
