### ISSUE TITLE
Server is immediately terminated when an invalid key is attempted to be saved

### ISSUE THREAD

**Issue by yuri-sergiichuk** [urish/firebase-server#126]
I do know that some characters are not allowed to be keys in Firebase tree structure, but I'm not sure whether it is appropriate to kill the whole running server in case such illegal character is supplied.

For my personal liking, I'd say that the server should print an error and the stack trace, but it definitely should still be alive.

Just in case, here is the stack trace I've received from the server:
```
@firebase/database/dist/index.node.cjs.js:1469
                    throw new Error(errorPrefix +
                    ^

Error: Reference.update failed: First argument  contains an invalid key (john.doe@example.com) in property 'domains.example.byOperator'.  Keys must be non-empty strings and can't contain ".", "#", "$", "/", "[", or "]"
    at /home/<machine_name>/.nvm/versions/node/v6.9.0/lib/node_modules/firebase-server/node_modules/@firebase/database/dist/index.node.cjs.js:1469:27
    at Object.forEach (/home/<machine_name>/.nvm/versions/node/v6.9.0/lib/node_modules/firebase-server/node_modules/@firebase/util/dist/index.node.cjs.js:841:13)
    at validateFirebaseData (/home/<machine_name>/.nvm/versions/node/v6.9.0/lib/node_modules/firebase-server/node_modules/@firebase/database/dist/index.node.cjs.js:1462:14)
    at /home/<machine_name>/.nvm/versions/node/v6.9.0/lib/node_modules/firebase-server/node_modules/@firebase/database/dist/index.node.cjs.js:1553:9
    at Object.forEach (/home/<machine_name>/.nvm/versions/node/v6.9.0/lib/node_modules/firebase-server/node_modules/@firebase/util/dist/index.node.cjs.js:841:13)
    at validateFirebaseMergeDataArg (/home/<machine_name>/.nvm/versions/node/v6.9.0/lib/node_modules/firebase-server/node_modules/@firebase/database/dist/index.node.cjs.js:1551:10)
    at Reference.update (/home/<machine_name>/.nvm/versions/node/v6.9.0/lib/node_modules/firebase-server/node_modules/@firebase/database/dist/index.node.cjs.js:13989:9)
    at IncomingMessage.request.on (/home/<machine_name>/.nvm/versions/node/v6.9.0/lib/node_modules/firebase-server/dist/lib/http-server.js:28:38)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)

```

**Comment by urish** [comment]
Good call!

A pull request (with appropriate test case) is welcome :-)

**Comment by yuri-sergiichuk** [comment]
I'd really like to participate, it's just I'm so not into JS :( Wanna re-write the server in Java?))

**Comment by urish** [comment]
Closing, as the project has been deprecated. See #150 for details.
