### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by israelariel** [urish/firebase-server#66]
Hi everyone. 
First i ll like to thanks for such a proyect. I have a problem and i don't have any clue. I using windows 10 with the  nodejs version 6.9.1 and npm version 3.10.8. I don't know why but i think i cant get all the dependencies instaled. After run de command:
$npm install --save-dev firebase-server
and 
$\node_modules.bin\firebase-server
i get the error:
Error: Cannot find module 'firebase'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\israel\Documents\Dev\Firebase\firebase-server-master\node_modules\firebase-server\index.js:17:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Any help?
thanks

**Comment by degroote22** [comment]
try https://github.com/urish/firebase-server/issues/58#issuecomment-253801914

**Comment by dylanjha** [comment]
fixed in https://github.com/urish/firebase-server/issues/66 

@israelariel until the next version is released you'll have to also install firebase:

> npm install firebase --save
