### ISSUE TITLE
Error while connecting to the local server

### ISSUE THREAD

**Issue by shivensinha4** [urish/firebase-server#98]
When I change the database URL of my Firebase config to the local URL, I get this error:
`Error: FIREBASE FATAL ERROR: test.firebase.localhost is no longer supported. Please use <YOUR FIREBASE>.firebaseio.com instead
    at Error (native)
    at Sb (C:\Users\HOME-PC\Desktop\webdev\chat\node_modules\firebase\database-node.js:51:277)
    at Tb (C:\Users\HOME-PC\Desktop\webdev\chat\node_modules\firebase\database-node.js:52:494)
    at Object.firebase.INTERNAL.registerService.Reference [as database] (C:\Users\HOME-PC\Desktop\webdev\chat\node_modules\firebase\database-node.js:256:241)
    at FirebaseAppImpl._getService (C:\Users\HOME-PC\Desktop\webdev\chat\node_modules\firebase\app\firebase_app.js:138:70)
    at FirebaseAppImpl.(anonymous function) [as database] (C:\Users\HOME-PC\Desktop\webdev\chat\node_modules\firebase\app\firebase_app.js:297:39)
    at Object.serviceNamespace [as database] (C:\Users\HOME-PC\Desktop\webdev\chat\node_modules\firebase\app\firebase_app.js:281:40)
    at module.exports (C:\Users\HOME-PC\Desktop\webdev\chat\server\socketEvents.js:14:27)
    at Object.<anonymous> (C:\Users\HOME-PC\Desktop\webdev\chat\server.js:20:1)
    at Module._compile (module.js:570:32)`
My config currently is
`var config = {
    databaseURL: "ws://test.firebase.localhost"
  };`
What am I doing wrong?

**Comment by urish** [comment]
You can try changing it to test.firebaseio.com (and update your hosts file accordingly) and check if it does the trick

**Comment by shivensinha4** [comment]
I made the necessary changes, and even though I mention ws:// in the db url in config, it feel that it somehow points to https://, because I get a blank page with text (I'm using Firebase with Node and Express)
`Upgrade Required`
I guess that it's HTTP status 426.

**Comment by urish** [comment]
Seems like firebase/firebase-js-sdk#426 will fix this.
